-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating VARCHAR(1)
);

-- insert some test data
insert into bookmarks (title, url, description, rating)
values
    ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
    ('Google', 'https://www.google.com', 'Where we find everything else', 4),
    ('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation', 5);
